name: Size

on: [pull_request]

env: # Set environment variables for every job and step in this workflow
  CLICOLOR: "1" # Enable colors for *NIX commands
  PY_COLORS: "1" # Enable colors for Python-based utilities
  FORCE_COLOR: "1" # Force colors in the terminal
  STREAMLINE_SECRET: ${{ secrets.STREAMLINE_SECRET }}
  STREAMLINE_FAMILIES: ${{ secrets.STREAMLINE_FAMILIES }}

jobs:
  measure:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Node
        uses: ./.github/actions/node

      - name: Size limit
        uses: andresz1/size-limit-action@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          skip_step: install
          build_script: size:build
